config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :sectors
  resources :neighborhoods
  resources :maternity_assistances
  resources :registrations
  resources :children
  resources :mothers
  get 'welcome/index'
  root 'welcome#index'
  resources :teams

    

end

app/models/maternity_assistance.rb
class MaternityAssistance < ActiveRecord::Base
end

app/controllers/maternity_assistances_controller.rb
class MaternityAssistancesController < ApplicationController
  before_action :set_maternity_assistance, only: [:show, :edit, :update, :destroy]
  before_action :set_mother, only: [:create,:new, :show, :edit, :update, :destroy]

  # GET /maternity_assistances
  # GET /maternity_assistances.json
  def index
    @maternity_assistances = MaternityAssistance.all
  end

  # GET /maternity_assistances/1
  # GET /maternity_assistances/1.json
  def show
  end

  # GET /maternity_assistances/new
  def new
    @maternity_assistance = MaternityAssistance.new
  end

  # GET /maternity_assistances/1/edit
  def edit
  end

  # POST /maternity_assistances
  # POST /maternity_assistances.json
  def create
    @maternity_assistance = MaternityAssistance.new(maternity_assistance_params)

    respond_to do |format|
      if @maternity_assistance.save
        format.html { redirect_to @maternity_assistance, notice: 'Maternity assistance was successfully created.' }
        format.json { render :show, status: :created, location: @maternity_assistance }
      else
        format.html { render :new }
        format.json { render json: @maternity_assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maternity_assistances/1
  # PATCH/PUT /maternity_assistances/1.json
  def update
    respond_to do |format|
      if @maternity_assistance.update(maternity_assistance_params)
        format.html { redirect_to @maternity_assistance, notice: 'Maternity assistance was successfully updated.' }
        format.json { render :show, status: :ok, location: @maternity_assistance }
      else
        format.html { render :edit }
        format.json { render json: @maternity_assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maternity_assistances/1
  # DELETE /maternity_assistances/1.json
  def destroy
    @maternity_assistance.destroy
    respond_to do |format|
      format.html { redirect_to maternity_assistances_url, notice: 'Maternity assistance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maternity_assistance
      @maternity_assistance = MaternityAssistance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maternity_assistance_params
      params.require(:maternity_assistance).permit(:startDate, :endDate, :mother)
    end
    def set_mother

      @mother = Mother.all
      
    end
end

app/helpers/maternity_assistances_helper.rb
module MaternityAssistancesHelper
end

app/views/maternity_assistances/_form.html.erb
<%= form_for @maternity_assistance, :html => { :class => "form-horizontal maternity_assistance" } do |f| %>

  <% if @maternity_assistance.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@maternity_assistance.errors.count, "error") %> prohibited this maternity_assistance from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @maternity_assistance.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :startDate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :startDate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:startDate) %>
  </div>
  <div class="form-group">
    <%= f.label :endDate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endDate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endDate) %>
  </div>
  <div class="form-group">
    <%= f.label :mother_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
     <%= f.collection_select :mother_id, @mother.all, :id, :nameMother, include_blank: true %>
    </div>
    <%=f.error_span(:mother_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                maternity_assistances_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/maternity_assistances/edit.html.erb
<%- model_class = MaternityAssistance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/maternity_assistances/index.html.erb
<%- model_class = MaternityAssistance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:startDate) %></th>
      <th><%= model_class.human_attribute_name(:endDate) %></th>
      <th><%= model_class.human_attribute_name(:mother_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @maternity_assistances.each do |maternity_assistance| %>
      <tr>
        <td><%= link_to maternity_assistance.id, maternity_assistance_path(maternity_assistance) %></td>
        <td><%= maternity_assistance.startDate %></td>
        <td><%= maternity_assistance.endDate %></td>
        <td><%= maternity_assistance.mother_id %></td>
        <td><%=l maternity_assistance.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_maternity_assistance_path(maternity_assistance), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      maternity_assistance_path(maternity_assistance),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_maternity_assistance_path,
            :class => 'btn btn-primary' %>

app/views/maternity_assistances/new.html.erb
<%- model_class = MaternityAssistance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/maternity_assistances/show.html.erb
<%- model_class = MaternityAssistance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:startDate) %>:</strong></dt>
  <dd><%= @maternity_assistance.startDate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endDate) %>:</strong></dt>
  <dd><%= @maternity_assistance.endDate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mother_id) %>:</strong></dt>
  <dd><%= @maternity_assistance.mother_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              maternity_assistances_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_maternity_assistance_path(@maternity_assistance), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              maternity_assistance_path(@maternity_assistance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
              :class => 'btn btn-danger' %>