config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :sectors
  resources :neighborhoods
  resources :maternity_assistances
  resources :registrations
  resources :children
  resources :mothers
  get 'welcome/index'
  root 'welcome#index'
  resources :teams

    

end

app/models/sector.rb
class Sector < ActiveRecord::Base
    validates :codeSector, presence: true
    validates :descriptionSector, presence: true
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Setor salvo com sucesso' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Setor atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Setor apagado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:codeSector, :descriptionSector)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_for @sector, :html => { :class => "form-horizontal sector" } do |f| %>

  <% if @sector.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sector.errors.count, "erros") %> impedem o Setor de ser salvo:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sector.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codeSector, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :codeSector, :class => 'form-control' %>
    </div>
    <%=f.error_span(:codeSector) %>
  </div>
  <div class="form-group">
    <%= f.label :descriptionSector, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descriptionSector, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descriptionSector) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sectors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sectors/edit.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar Setor'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sectors/index.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t 'Setores' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th style="width: 5%">ID </th>
      <th style="width: 15%">Código Setor </th></th>
      <th style="width: 40%">Descrição </th>
      <th><%= model_class.human_attribute_name(:created_at,) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sectors.each do |sector| %>
      <tr>
        <td><%= link_to sector.id, sector_path(sector) %></td>
        <td><%= sector.codeSector %></td>
        <td><%= sector.descriptionSector %></td>
        <td><%=l sector.created_at, :format => :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sector_path(sector), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sector_path(sector),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza ?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sector_path,
            :class => 'btn btn-success' %>

app/views/sectors/new.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo Setor'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sectors/show.html.erb
<%- model_class = Sector -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:codeSector) %>:</strong></dt>
  <dd><%= @sector.codeSector %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descriptionSector) %>:</strong></dt>
  <dd><%= @sector.descriptionSector %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              sectors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sector_path(@sector), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sector_path(@sector),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
              :class => 'btn btn-danger' %>