config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :sectors
  resources :neighborhoods
  resources :maternity_assistances
  resources :registrations
  resources :children
  resources :mothers
  get 'welcome/index'
  root 'welcome#index'
  resources :teams

    

end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :neighborhood

  validates :neighborhood, presence: true
  validates :nameSchool, presence: true
  validates :vacanciesSchool, presence: true

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :set_neighborhood, only: [:create, :new, :show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'Escola salva com sucesso' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'Escola atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'Escola apagada com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:nameSchool, :vacanciesSchool, :neighborhood_id)
    end
    def set_neighborhood

      @neighborhood = Neighborhood.all

    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for @school, :html => { :class => "form-horizontal school" } do |f| %>

  <% if @school.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@school.errors.count, "erros") %> impedem a Escola de ser salva</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @school.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nameSchool, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nameSchool, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nameSchool) %>
  </div>
  <div class="form-group">
    <%= f.label :vacanciesSchool, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :vacanciesSchool, :class => 'form-control' %>
    </div>
    <%=f.error_span(:vacanciesSchool) %>
  </div>
  <div class="form-group">
    <%= f.label :neighborhood_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :neighborhood_id, @neighborhood.all, :id, :nameNeighborhood, include_blank: true %>
    </div>
    <%=f.error_span(:neighborhood_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                schools_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/schools/edit.html.erb
<%- model_class = School -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/schools/index.html.erb
<%- model_class = School -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th style="width: 2%">ID</th>
      <th style="width: 38%">Nome</th>
      <th style="width: 5%">Vagas</th>
      <th style="width: 27%">Bairro</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= link_to school.id, school_path(school) %></td>
        <td><%= school.nameSchool %></td>
        <td><%= school.vacanciesSchool %></td>
        <td><%= school.neighborhood.nameNeighborhood %></td>
        <td><%=l school.created_at, :format => :short  %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_school_path(school), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      school_path(school),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_school_path,
            :class => 'btn btn-success' %>

app/views/schools/new.html.erb
<%- model_class = School -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nova %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/schools/show.html.erb
<%- model_class = School -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nameSchool) %>:</strong></dt>
  <dd><%= @school.nameSchool %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vacanciesSchool) %>:</strong></dt>
  <dd><%= @school.vacanciesSchool %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neighborhood_id) %>:</strong></dt>
  <dd><%= @school.neighborhood_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              schools_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_school_path(@school), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              school_path(@school),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
              :class => 'btn btn-danger' %>