config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :sectors
  resources :neighborhoods
  resources :maternity_assistances
  resources :registrations
  resources :children
  resources :mothers
  get 'welcome/index'
  root 'welcome#index'
  resources :teams

    

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :sector

  validates :nameNeighborhood, presence: true
  validates :sector_id, presence: true

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]
  before_action :set_sector, only: [:create, :new, :show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Bairro salvo com sucesso.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Bairro atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Bairro apagado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:nameNeighborhood, :sector_id)
    end
    def set_sector

      @sector = Sector.all

    end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<%= form_for @neighborhood, :html => { :class => "form-horizontal neighborhood" } do |f| %>

  <% if @neighborhood.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@neighborhood.errors.count, "erros") %> impedem o Bairro de ser salvo</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @neighborhood.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nameNeighborhood, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nameNeighborhood, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nameNeighborhood) %>
  </div>
  <div class="form-group">
    <%= f.label :sector_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :sector_id, @sector.all, :id, :descriptionSector, include_blank: true %>
    </div>
    <%=f.error_span(:sector_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                neighborhoods_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/neighborhoods/edit.html.erb
<%- model_class = Neighborhood -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighborhoods/index.html.erb
<%- model_class = Neighborhood -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th style="width: 30%">Nome </th>
      <th style="width: 30%">Setor </th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= link_to neighborhood.id, neighborhood_path(neighborhood) %></td>
        <td><%= neighborhood.nameNeighborhood %></td>
        <td><%= neighborhood.sector.descriptionSector %></td>
        <td><%=l neighborhood.created_at , :format => :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_neighborhood_path(neighborhood), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      neighborhood_path(neighborhood),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_neighborhood_path,
            :class => 'btn btn-success' %>

app/views/neighborhoods/new.html.erb
<%- model_class = Neighborhood -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighborhoods/show.html.erb
<%- model_class = Neighborhood -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nameNeighborhood) %>:</strong></dt>
  <dd><%= @neighborhood.nameNeighborhood %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sector_id) %>:</strong></dt>
  <dd><%= @neighborhood.sector_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              neighborhoods_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_neighborhood_path(@neighborhood), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              neighborhood_path(@neighborhood),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
              :class => 'btn btn-danger' %>